### ISSUE TITLE
CSS Cleanup tips

### ISSUE THREAD

**Issue by fisher60** [fisher60/portfolio#2]
https://github.com/fisher60/portfolio/blob/main/portfolio/src/components/category.css#L17-L27
```css
.category-title {
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
}
```

https://github.com/fisher60/portfolio/blob/main/portfolio/src/components/category.css#L39-L48
```css
.category img {
  max-height: 100%;
  width: auto;
}
```
```css
.category-container {
  min-width: 250px;
}

.categories-container {
    flex-wrap: wrap;

}
```
